# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test_1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test_1

  target 'Test_1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test_1UITests' do
    # Pods for testing
  end

end
